# -*- coding: utf-8 -*-
"""ML TASSK2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1396v8pR9Jz1_6GGaBcghAGi2ZnYycavc
"""

!pip install scikit-learn
!pip  install pandas

import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

"""LOAD AND READ DATASET"""

train_data = pd.read_csv("/content/fraudTrain.csv")

train_data.info()

train_data.describe()

train_data.dtypes

train_data.columns

train_data.isnull().sum()

train_data['job'].fillna(train_data['job'].mode()[0], inplace=True)
train_data['dob'].fillna(train_data['dob'].mode()[0], inplace=True)
train_data['trans_num'].fillna(train_data['trans_num'].mode()[0], inplace=True)
train_data['unix_time'].fillna(train_data['unix_time'].mode()[0], inplace=True)
train_data['merch_lat'].fillna(train_data['merch_lat'].mode()[0], inplace=True)
train_data['merch_long'].fillna(train_data['merch_long'].mode()[0], inplace=True)
train_data['is_fraud'].fillna(train_data['is_fraud'].mode()[0], inplace=True)

train_data.isna().sum()

"""DATA PRE PREOCESSING"""

train_data["trans_date_trans_time"] = pd.to_datetime(train_data["trans_date_trans_time"])
train_data["dob"] = pd.to_datetime(train_data["dob"])
train_data

train_data.drop(columns=['Unnamed: 0','cc_num','first', 'last', 'street', 'city', 'state', 'zip', 'dob', 'trans_num','trans_date_trans_time'],inplace=True)
train_data

#Drop all rows that contain missing values
train_data.dropna(ignore_index=True)
train_data

train_data.dropna(ignore_index=True)

encoder = LabelEncoder()
train_data["merchant"] = encoder.fit_transform(train_data["merchant"])
train_data["category"] = encoder.fit_transform(train_data["category"])
train_data["gender"] = encoder.fit_transform(train_data["gender"])
train_data["job"] = encoder.fit_transform(train_data["job"])

train_data

"""EDA"""

exit_counts = train_data["is_fraud"].value_counts()
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)  # Subplot for the pie chart
plt.pie(exit_counts, labels=["No", "YES"], autopct="%0.0f%%")
plt.title("is_fraud Counts")
plt.tight_layout()  # Adjust layout to prevent overlapping
plt.show()

"""TRAIN THE MODEL"""

X = train_data.drop(columns=["is_fraud"], inplace = False)
Y = train_data["is_fraud"]

model = SVC()
model.fit(X, Y)

model.score(X, Y)

"""TEST MODEL"""

test_data = pd.read_csv("/content/fraudTest.csv")
test_data

test_data.isna().sum()

test_data.drop(columns=['Unnamed: 0','cc_num','first', 'last', 'street', 'city', 'state', 'zip', 'dob', 'trans_num','trans_date_trans_time'],inplace=True)
test_data

test_data['merch_lat'].fillna(test_data['merch_lat'].mode()[0], inplace=True)
test_data['merch_long'].fillna(test_data['merch_long'].mode()[0], inplace=True)
test_data['is_fraud'].fillna(test_data['is_fraud'].mode()[0], inplace=True)
test_data['unix_time'].fillna(test_data['unix_time'].mode()[0], inplace=True)

test_data.isna().sum()

encoder = LabelEncoder()
test_data["merchant"] = encoder.fit_transform(test_data["merchant"])
test_data["category"] = encoder.fit_transform(test_data["category"])
test_data["gender"] = encoder.fit_transform(test_data["gender"])
test_data["job"] = encoder.fit_transform(test_data["job"])

test_data

X_test = test_data.drop(columns=["is_fraud"], inplace = False)
Y_test = test_data["is_fraud"]

y_pred = model.predict(X_test)
y_pred

accuracy = accuracy_score(test_data['is_fraud'],y_pred)
accuracy

